# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Create GDM transformed grids for big grids
#' @description Calculate the dissimilarity between specified pairs of sites. 
#' @param site_spp (matrix) A matrix of the indices for species (col2) occurring in each site (col1), with each row an occurrence
#' @param pair_rows (matrix) A matrix of the site index for site 1 (col 1) and site 2 (col 2) in each pair of sites (rows)
#' @param site_rich (vector) A vector giving the total number of species in each site (element)
#' @param max_richness (integer)
#' @return Vector, the Sorensen dissimilarity between the specified pairs.
#' @examples output = PairsDissim(site.spp, ij.pairs, site.rich, max.rich)
#' @export
BigGridTransform <- function(nrows, ncols, nlayers, InFilePaths, OutFilePaths) {
    .Call('_gdmEngine_BigGridTransform', PACKAGE = 'gdmEngine', nrows, ncols, nlayers, InFilePaths, OutFilePaths)
}

#' @title Compositional dissimilarity calculation for specified pairs of sites
#' @description Calculate the dissimilarity between specified pairs of sites. 
#' @param site_spp (matrix) A matrix of the indices for species (col2) occurring in each site (col1), with each row an occurrence
#' @param pair_rows (matrix) A matrix of the site index for site 1 (col 1) and site 2 (col 2) in each pair of sites (rows)
#' @param site_rich (vector) A vector giving the total number of species in each site (element)
#' @param max_richness (integer)
#' @return Vector, the Sorensen dissimilarity between the specified pairs.
#' @examples output = PairsDissim(site.spp, ij.pairs, site.rich, max.rich)
#' @export
PairsDissim <- function(site_spp, pair_rows, site_rich, max_richness) {
    .Call('_gdmEngine_PairsDissim', PACKAGE = 'gdmEngine', site_spp, pair_rows, site_rich, max_richness)
}

#' @title Distance calculation for specified pairs
#' @description Calculate the distance between specified pairs. 
#' @param env_vars (matrix) A matrix of the standardised environment variables (cols) for each site (rows)
#' @param pair_rows (matrix) A matrix of the row index in 'env_vars' for site 1 (col 1) and site 2 (col 2) in each pair of sites (rows)
#' @return Vector, the Euclidean distance between the specified pairs.
#' @examples output = PairsDist(std.site.env.vars, ij.pairs)
#' @importFrom Rcpp cppFunction
#' @export
PairsDist <- function(env_vars, pair_rows) {
    .Call('_gdmEngine_PairsDist', PACKAGE = 'gdmEngine', env_vars, pair_rows)
}

